name: Lint and Deploy
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install eslint
      run: npm install eslint --save-dev
    - name: Lint
      run: npx eslint scripts.js --no-config-lookup

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Configurar usuario de Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./

