name: DevSkim Security Scan

on: [push, pull_request]  # Trigger the workflow on push or pull request events.

jobs:
  security_scan:
    runs-on: ubuntu-latest  # Specifies the runner environment.
    steps:
      - name: Checkout code  # Checkout the repository code.
        uses: actions/checkout@v2
      
      - name: Run DevSkim  # Run the DevSkim action to analyze the code.
        uses: microsoft/DevSkim-Action@v1.0.14
        with:
          directory-to-scan: ''  # Scan the entire repository. Specify a path to scan a specific directory.
          should-scan-archives: true  # Set to true to include archive scanning.
          output-filename: 'devskim-results.sarif'  # The filename for output results.
          output-directory: './security-reports'  # Directory to store the output results.
          ignore-globs: '**/.git/**, **/bin/**'  # Glob patterns to ignore during scanning.
          exclude-rules: ''  # Specify rule IDs to exclude, if necessary.
          options-json: ''  # Path to a JSON file with additional options, if needed.
          extra-options: ''  # Any additional command line arguments.
