  - name: DevSkim
  uses: microsoft/DevSkim-Action@v1.0.14
  with:
    # The sub directory of the repository root to scan. Repository root used by default.
    directory-to-scan: # optional, default is GITHUB_WORKSPACE
    # Optionally scan the contents of archives.
    should-scan-archives: # optional
    # The filename for the output.
    output-filename: # optional, default is devskim-results.sarif
    # The sub directory for the output under GITHUB_WORKSPACE.
    output-directory: # optional, default is GITHUB_WORKSPACE
    # Optional comma separated list of file globs to ignore when scanning.
    ignore-globs: # optional, default is **/.git/**,**/bin/**
    # Optional comma separated list of rule IDs to ignore
    exclude-rules: # optional, default is 
    # Optional path in the repository containing a json to provide to the --options-json argument
    options-json: # optional, default is 
    # Provide any other command line arguments for the DevSkim analyze command. See DevSkim documentation for usage instructions.
    extra-options: # optional, default is 
          
